---
- name: this playbook install httpd
  hosts: all
  become: true
  tasks:
    - name: install pacakege
      yum:
        name: httpd
        state: installed
      notify: start apache
  handlers: #if upper notify not work this handlers will not execute
    - name: install pacakege
      service:
        name: httpd
        state: started